#!/bin/sh
#
# usage: journal [DATE]
#
# Opens your $EDITOR with an empty markdown file waiting
# to be filled. If DATE is not given it defaults to today.
#
# Environemnt variables:
#  $$EDITOR or $JOURNAL_EDITOR - sets what program should open the journal
#  $JOURNAL - sets the path to the journal's folder
#
# The date string takes a humanized format, documented at:
# https://www.gnu.org/software/coreutils/manual/html_node/Date-input-formats.html
#
# Examples:
#
# If today is February 12th, 2017 then
#   journal   # opens $JOURNAL/2017/12
#   journal Aug 12 2019  # opens $JOURNAL/2019/08/12.md
#
#   journal yesterday          # opens $JOURNAL/2017/02/11.md
#   journal tomorrow           # opens $JOURNAL/2017/02/13.md
#   journal last wednesday     # opens $JOURNAL/2017/02/08.md
#   journal last month         # opens $JOURNAL/2017/01/12.md
#   journal 2 weeks ago 2 days # opens $JOURNAL/2017/01/31.md
#   journal 3 months ago 1 week 4 days
#                              # opens $JOURNAL/2016/10/23.md
#
#   export JOURNAL=/mnt/remote/journal2
#   journal 2 day  # opens /mnt/remote/journal2/2017/02/14.md
#
# And some more clever combinations:
#   EDITOR="wc -w" journal last month  # see how many words you wrote exactly one month ago
#   EDITOR="head" journal monday # see what you were doing at the start of the week
#   EDITOR="tail" journal last friday # see what you did at the end of last week
#
# (c) 2020 nick@kousu.ca, MIT License

# TODO:
# - [ ] support BSD `date` as well; probably just by disallowing the yesterday/tomorrow feature.
# - [ ] small bug: because this calls date multiple times, it's possible (e.g. at midnight,
#       new years, ends of months for the results to be inconsistent.
#       it would be safer to call date *once* to get the date value, then feed it back in successively to parse it

set -e  # catch errors immediately

# -----------------------------------------------------------------------------
# git-sync.sh

git-syncable() {
  if ! git -C "$1" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    # are we inside git?
    # if not, the user isn't using git, so just ignore
    return 1
  fi

  if ! REMOTES=$(git -C "$1" remote 2>&1) || [ -z "$REMOTES" ]; then

    # pretty-print the path "$1" relative to $HOME, or if not possible use the absolute path
    path="$(realpath --relative-to="$HOME" --relative-base="$HOME" "$1")"
    if [ "${path#/}" = "$path" ]; then
      # if the result was an absolute path then it wasn't relative to $HOME
      path='~/'"$path"
    fi

    echo "There is no remote server to sync to; you should consider adding one:"
    printf "\tgit -C \"%s\" remote add origin your@remote:repo\n" "$path"
    return 1
  fi

  return 0
}

git-sync() {
  # The git commands are all `set -x` so that their output
  # comes with a header explaining what it is in the log
  # (but the logic around them is hidden)

  # commit
  (set -x; git -C "$1" stage -v --all) # NB: --all means stage deletions too, not just new and modified files
  if ! git -C "$1" diff --staged --quiet; then

    (set -x; git -C "$1" commit -m "Syncing")
  fi

  # pull
  if git -C "$1" rev-parse @{upstream} >/dev/null 2>&1; then
    # only pull if there's an upstream branch for this branch
    # - an upstream may be local OR remote;
    #   - `git config branch.autoSetupMerge always` causes local upstreams
    #   - TODO: warn if the upstream is local?
    # - an upstream will usually be *set* by the following git push if missing,
    #   so this is only skipped on the *first* run.

    # git pull
    #
    # Separate fetch + rebase/merge so that we can distinguish error cases:
    # - network/auth problems fail at fetch
    # - merge conflicts fail at rebase/merge
    (set -x; git -C "$1" fetch)
    branch=$(git -C "$1" rev-parse --abbrev-ref HEAD)
    rebase=$(git -C "$1" config --bool "branch.${branch}.rebase" 2>/dev/null \
         || git -C "$1" config --bool pull.rebase 2>/dev/null)
    if [ "${rebase}" = "true" ]; then
      # https://stackoverflow.com/questions/44953117/can-git-tell-me-if-a-rebase-will-conflict-without-actually-rebasing :
      (set -x; git -C "$1" rebase) || (ORIG_RC=$?; (set -x; git -C "$1" rebase --abort) && exit $ORIG_RC);
    else
      (set -x; git -C "$1" merge --no-ff --no-edit) || (ORIG_RC=$?; (set -x; git -C "$1" merge --abort) && exit $ORIG_RC);
    fi
  fi

  # push
  # in most git configurations, push will create an upstream so long as there is at least one remote defined
  # TODO: can we handle the cases where push
  (set -x; git -C "$1" push)
}

# -----------------------------------------------------------------------------

suffix() {
  # compute date suffix
  # inspired by https://wmfexcel.com/2014/11/08/date-formats-a-trick-to-format-date-with-st-nd-rd-th/
  echo -n "$1"
  case "$1" in
    *1)
      echo -n "st"
      ;;
    *2)
      echo -n "nd"
      ;;
    *3)
      echo -n "rd"
      ;;
    *4|*5|*6|*7|*8|*9|*0)
      echo -n "th"
      ;;
  esac
  echo
}

strip() {
    # strip surrounding whitespace
    # this is really silly
    echo $1
}

header() {
  # print a header for the journal file, like
  #
  #   Saturday June the 27th, 2020
  #   ============================
  #
  D=$(suffix "$(date +"%_d")")
  D=$(strip $D)
  HEADER="$(date +"%A %B the ${D}, %Y")"
  echo "$HEADER"
  echo "$HEADER" | sed s/./=/g  # underline
}

WHEN=${@:-now}
date() {
    /bin/date -d "$WHEN" "$@"
}

if [ -z "$JOURNAL_EDITOR" ]; then
  for editor in "$EDITOR" nano vi; do
    if command -v $EDITOR >/dev/null ; then
      export JOURNAL_EDITOR="$editor"
      break;
    fi
  done

  if [ -z "$JOURNAL_EDITOR" ]; then
    echo "error: \$JOURNAL_EDITOR undefined and no fallback installed." >/dev/stderr
    exit 1
  fi
fi

: ${JOURNAL:=~/Journal}
TODAY="$(date +"%Y/%m/%d").md"

if [ ! -e "${JOURNAL}" ]; then
  read -r -p "${JOURNAL} does not exist. Would you like to create it? [y/N] " RESP
  case "$RESP" in
    [yY])
      mkdir -p "${JOURNAL}"
      git -C "${JOURNAL}" init
      ;;
    *)
      exit 0
      ;;
  esac
fi

mkdir -p "$(dirname "${JOURNAL}/${TODAY}")"

if git-syncable "${JOURNAL}"; then
  # sync in the background
  # this runs an immediate sync in parallel with opening the editor
  # there's a risk that sync edits "$TODAY"; if so .. hm.
  (
    # subtle: relay TERM signals to the *sleep* but *not* to the git-sync
    # because we don't want to risk interrupting it
    trap '[ -n $SLEEP_PID ] && kill -TERM $SLEEP_PID; wait' TERM
    while true; do
      git-sync "${JOURNAL}";
      sleep 60 & SLEEP_PID=$!; wait $SLEEP_PID;
    done
  ) >/dev/null &
  SYNC_PID=$!

  # and after
  trap 'kill $SYNC_PID; wait $SYNC_PID; git-sync "${JOURNAL}"' EXIT
fi

cd "${JOURNAL}"
${JOURNAL_EDITOR} "$TODAY"
